In [4]:
# 创建一些实验样本。文档来自于斑点犬爱好者留言板。
def loadDataSet():
    postingList=[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
                 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
                 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
                 ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
                 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
                 ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]
    classVec = [0,1,0,1,0,1]      # 1 代表侮辱性言论, 0 代表正常言论
    return postingList,classVec

In [2]:
listOPosts,listClasses = loadDataSet()
listOPosts

[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
 ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
 ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]

In [3]:
vocabSet = set([])    # 创建集合set(),{}是创建一个空字典
for i in listOPosts:
    vocabSet = vocabSet | set(i)
    print(vocabSet)

{'help', 'problems', 'has', 'please', 'my', 'flea', 'dog'}
{'park', 'stupid', 'please', 'my', 'him', 'to', 'has', 'dog', 'not', 'maybe', 'help', 'problems', 'flea', 'take'}
{'dalmation', 'park', 'so', 'please', 'my', 'him', 'dog', 'not', 'help', 'take', 'love', 'I', 'to', 'has', 'problems', 'maybe', 'cute', 'is', 'stupid', 'flea'}
{'dalmation', 'park', 'worthless', 'so', 'please', 'my', 'him', 'dog', 'stop', 'not', 'help', 'take', 'love', 'garbage', 'I', 'to', 'has', 'problems', 'maybe', 'cute', 'posting', 'is', 'stupid', 'flea'}
{'dalmation', 'park', 'worthless', 'ate', 'so', 'please', 'my', 'him', 'steak', 'dog', 'stop', 'not', 'help', 'take', 'love', 'garbage', 'I', 'to', 'has', 'problems', 'mr', 'maybe', 'cute', 'posting', 'licks', 'is', 'how', 'stupid', 'flea'}
{'dalmation', 'park', 'food', 'worthless', 'ate', 'so', 'please', 'my', 'him', 'steak', 'quit', 'dog', 'stop', 'not', 'help', 'take', 'love', 'garbage', 'buying', 'I', 'to', 'has', 'problems', 'mr', 'maybe', 'cute', 'postin

In [19]:
list1 = [1, 1, 3, 2, 3]
s = set(list1)
print(s)

s.add(9)  # s.add([2,3]) 错误，add函数只能增加与原集合相同类型的元素

s.update([3, 5, 6])  # s.update(5) 错误，update更新集合时传入的是一个可迭代对象
print(s)

{1, 2, 3}
{1, 2, 3, 5, 6, 9}


In [8]:
i = set()
print(type(i))

<class 'set'>


In [9]:
vocabSet = set()
for i in listOPosts:
    vocabSet = vocabSet | set(i)
    print(vocabSet)

{'help', 'problems', 'has', 'please', 'my', 'flea', 'dog'}
{'park', 'stupid', 'please', 'my', 'him', 'to', 'has', 'dog', 'not', 'maybe', 'help', 'problems', 'flea', 'take'}
{'dalmation', 'park', 'so', 'please', 'my', 'him', 'dog', 'not', 'help', 'take', 'love', 'I', 'to', 'has', 'problems', 'maybe', 'cute', 'is', 'stupid', 'flea'}
{'dalmation', 'park', 'worthless', 'so', 'please', 'my', 'him', 'dog', 'stop', 'not', 'help', 'take', 'love', 'garbage', 'I', 'to', 'has', 'problems', 'maybe', 'cute', 'posting', 'is', 'stupid', 'flea'}
{'dalmation', 'park', 'worthless', 'ate', 'so', 'please', 'my', 'him', 'steak', 'dog', 'stop', 'not', 'help', 'take', 'love', 'garbage', 'I', 'to', 'has', 'problems', 'mr', 'maybe', 'cute', 'posting', 'licks', 'is', 'how', 'stupid', 'flea'}
{'dalmation', 'park', 'food', 'worthless', 'ate', 'so', 'please', 'my', 'him', 'steak', 'quit', 'dog', 'stop', 'not', 'help', 'take', 'love', 'garbage', 'buying', 'I', 'to', 'has', 'problems', 'mr', 'maybe', 'cute', 'postin

In [16]:
vocabSet = set([])
for i in listOPosts:
    vocabSet.update(set(i))
    print(vocabSet)

{'help', 'problems', 'has', 'please', 'my', 'flea', 'dog'}
{'park', 'stupid', 'please', 'my', 'him', 'to', 'has', 'dog', 'not', 'maybe', 'help', 'problems', 'flea', 'take'}
{'dalmation', 'park', 'so', 'please', 'my', 'him', 'dog', 'not', 'help', 'take', 'love', 'I', 'to', 'has', 'problems', 'maybe', 'cute', 'is', 'stupid', 'flea'}
{'dalmation', 'park', 'worthless', 'so', 'please', 'my', 'him', 'dog', 'stop', 'not', 'help', 'take', 'love', 'garbage', 'I', 'to', 'has', 'problems', 'maybe', 'cute', 'posting', 'is', 'stupid', 'flea'}
{'dalmation', 'park', 'worthless', 'ate', 'so', 'please', 'my', 'him', 'steak', 'dog', 'stop', 'not', 'help', 'take', 'love', 'garbage', 'I', 'to', 'has', 'problems', 'mr', 'maybe', 'cute', 'posting', 'licks', 'is', 'how', 'stupid', 'flea'}
{'dalmation', 'park', 'food', 'worthless', 'ate', 'so', 'please', 'my', 'him', 'steak', 'quit', 'dog', 'stop', 'not', 'help', 'take', 'love', 'garbage', 'buying', 'I', 'to', 'has', 'problems', 'mr', 'maybe', 'cute', 'postin

In [ ]:
# del list  # 前面定义了list,使用list方法就不好使了。

In [22]:
list(vocabSet)

['dalmation',
 'park',
 'food',
 'worthless',
 'ate',
 'so',
 'please',
 'my',
 'him',
 'steak',
 'quit',
 'dog',
 'stop',
 'not',
 'help',
 'take',
 'love',
 'garbage',
 'buying',
 'I',
 'to',
 'has',
 'problems',
 'mr',
 'maybe',
 'cute',
 'posting',
 'licks',
 'is',
 'how',
 'stupid',
 'flea']

In [1]:
from numpy import *
zeros(5)

array([0., 0., 0., 0., 0.])

In [38]:
trainMatrix=[[1,0,1],[0,1,1],[0,0,0]]
trainCategory=[1,0,1]

In [39]:
numTrainDocs = len(trainMatrix)
print(numTrainDocs)
numWords = len(trainMatrix[0])
print(numWords)
pAbusive = sum(trainCategory)/float(numTrainDocs)
print(pAbusive)
p0Num = zeros(numWords); p1Num = zeros(numWords)
print(p0Num)
p0Denom = 0.0; p1Denom = 0.0

3
3
0.6666666666666666
[0. 0. 0.]


In [40]:
for i in range(numTrainDocs):
    if trainCategory[i] == 1:
        p1Num += trainMatrix[i]                # [1,0,1]+[0,0,0]
        p1Denom += sum(trainMatrix[i])         # 1+1+0+0 (不是类别为1的文档个数。若没有[0,0,0]分母还是2)
        print(p1Denom)
    else:
        p0Num += trainMatrix[i]                # [0,1,1]
        p0Denom += sum(trainMatrix[i])         # 1+1

2.0
2.0


In [41]:
p1Vect = p1Num/p1Denom        
p0Vect = p0Num/p0Denom

In [42]:
p1Vect

array([0.5, 0. , 0.5])

In [43]:
p0Vect

array([0. , 0.5, 0.5])

In [48]:
trainingSet = range(50)
trainingSet

range(0, 50)